#!/usr/bin/env python3
import sys


def show_addr(interface: str) -> int:
    if interface == 'wlan1':
        print('3: wlan1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500')
        print('    inet 192.168.31.4/24 brd 192.168.31.255 scope global wlan1')
        return 0
    if interface == 'eth0':
        print('2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500')
        print('    inet 192.168.1.100/24 brd 192.168.1.255 scope global eth0')
        return 0
    return 1


def main() -> int:
    args = sys.argv[1:]
    if len(args) == 4 and args[0] == '-4' and args[1] == 'addr' and args[2] == 'show':
        return show_addr(args[3])
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
